### ISSUE TITLE
SEGFAULT (0xC0000005) on Windows x64 when executing LOAD VECTOR

### ISSUE THREAD

**Issue by JayceVane** [LadybugDB/ladybug#499]
## Summary

`LOAD VECTOR` triggers a native access violation (segfault) on Windows x64, crashing the entire Node.js process. `INSTALL VECTOR` succeeds, but `LOAD VECTOR` immediately causes `STATUS_ACCESS_VIOLATION (0xC0000005)`.

## Environment

| Item | Value |
|------|-------|
| OS | Windows 11 x64 |
| Node.js | v22.15.0 |
| `@ladybugdb/core` | 0.15.4 |
| `lbugjs.node` | 13,227,008 bytes |
| CPU | (available on request) |

## Reproduction

```js
// test.mjs — place inside any project with @ladybugdb/core installed
import lbug from '@ladybugdb/core';
import fs from 'fs/promises';
import path from 'path';

const dbPath = './test.lbug';
await fs.mkdir(path.dirname(dbPath), { recursive: true });

const db = new lbug.Database(dbPath);
const conn = new lbug.Connection(db);

// This works fine
await conn.query('CREATE NODE TABLE Test (id STRING, PRIMARY KEY(id))');
console.log('Schema OK');

// This works fine
await conn.query('INSTALL VECTOR');
console.log('INSTALL VECTOR: OK');

// This crashes the process with 0xC0000005
await conn.query('LOAD VECTOR');
console.log('This line is never reached');

await conn.close();
```

```powershell
node test.mjs
# Output:
# Schema OK
# INSTALL VECTOR: OK
# LOAD VECTOR...
# <process exits with code -1073741819>
```

Exit code `-1073741819` = `0xC0000005` = `STATUS_ACCESS_VIOLATION`.

## Isolation Tests

All of the following work **without** any crash:

| Test | Result |
|------|--------|
| `require('@ladybugdb/core')` native addon load | ✅ |
| `new lbug.Database(path)` | ✅ |
| `new lbug.Connection(db)` | ✅ |
| 33 schema creation queries (tables, indexes, etc.) | ✅ all pass |
| `INSTALL VECTOR` | ✅ |
| `LOAD VECTOR` | 💥 SEGFAULT |
| `tree-sitter` native + `@ladybugdb/core` co-loaded | ✅ |
| `onnxruntime-node` + `@ladybugdb/core` co-loaded | ✅ |

The crash is **deterministic** and occurs on **every** `LOAD VECTOR` call, regardless of:
- Database content (empty or populated)
- Other native addons loaded before/after
- `--max-old-space-size` or `--stack-size` Node.js flags
- Working directory or path length

## Downstream Impact

This crash makes `gitnexus analyze` completely unusable on Windows, because `gitnexus` calls `initLbug()` → `doInitLbug()` → `loadVectorExtension()` → `conn.query('LOAD VECTOR')` during every repository indexing operation.

GitNexus issue: (pending)

## Suggested Fix

1. Investigate the VECTOR extension's native initialization on Windows x64 — likely an uninitialized pointer, missing SIMD fallback, or DLL dependency issue in the extension loading path.
2. As a workaround, consider making VECTOR extension loading optional/catchable so that the database remains usable (without vector search) even if the extension fails to load.

**Comment by adsharma** [comment]
Repros with 0.15.4 for me. But works on 0.16.1. 

Is it possible for you to upgrade and use the newer version?

**Comment by magyargergo** [comment]
I asked him to try to upgrade GitNexus to the latest version, hopefully, that will solve their issue.

**Comment by chiangchenghsin-hash** [comment]
Hi 👋 — I ran into this same crash on Windows 11 x64 with LadybugDB 0.18.0 (`LOAD VECTOR` → `STATUS_ACCESS_VIOLATION`), so I dug into the source and found the bug is still present in the 0.18.0 tag.

After tracing it down, the root cause turned out to be **four** separate issues in the VECTOR extension, not just the extension-loading path:

1. **`create_hnsw_index.cpp:60`** — MSVC rejects `const auto& table` calling the non-const `getNumTotalRows()` (`error C2662`). This one blocks Windows source builds entirely; clang/gcc tolerate it so it doesn't surface on Linux.
2. **`create_hnsw_index.cpp:64`** — `getStats(transaction).getTableCard()` can return 0 or a stale snapshot during uncommitted transactions, so `numNodes` is wrong and the HNSW graph gets sized incorrectly.
3. **`hnsw_index.cpp:672`** — `OnDiskHNSWIndex::finalize()` queries row count via `DUMMY_CHECKPOINT_TRANSACTION`, which returns 0 outside a checkpoint context. This makes `finalize()` **silently skip incremental writes**, so newly inserted nodes never get indexed. (This one is platform-agnostic — Linux doesn't crash but silently produces incomplete indexes, which might explain the low recall in #351.)
4. **`hnsw_rel_batch_insert.cpp:127`** — uninitialized CSR neighbor slots (`INVALID_OFFSET`) aren't filtered before being passed to `graphToNodeOffset()`, causing the out-of-bounds access that becomes `0xC0000005` on Windows.

Only #1 is Windows-specific; #2–#4 are logic bugs that affect all platforms (Linux just doesn't crash on them).

I've opened **#21** with fixes for all four, verified end-to-end on Windows 11 + MSVC 19.50 (`LOAD VECTOR` → `CREATE_VECTOR_INDEX` → `QUERY_VECTOR_INDEX` all pass after the patch). Didn't mean to step on anyone's toes — just wanted to share in case it's useful. Happy to adjust the PR if the approach or formatting needs tweaking.
