### ISSUE TITLE
Bug: fails to compile rust crate on MacOS

### ISSUE THREAD

**Issue by rcrisanti** [LadybugDB/ladybug#288]
### Ladybug version

v0.15.0 & v0.15.1

### What operating system are you using?

macOS Tahoe 26.3

### What happened?

I have a rust project that up until this point depended on kuzu. I was looking into migrating to ladybug. Unfortunately it seems like on v0.15.0 & v0.15.1 it is unable to compile. The output consists of a bunch of warnings along the lines of

```
ld: warning: object file (/private/var/folders/3w/mbn03l894kdg5b_wd52411s80000gp/T/tmp.Ss6ZJx9beD/ladybug-rust/target/debug/deps/liblbug-9c90a64812c0ac2a.rlib[9](82765364e21e5d72-ffi.rs.o)) was built for newer 'macOS' version (15.2) than being linked (11.0)
```

followed by an error
```
Undefined symbols for architecture arm64:
"_unsafe_yyjson_str_pool_grow", referenced from:
    lbug::binder::Binder::bindInsertNode(std::__1::shared_ptr<lbug::binder::NodeExpression>, std::__1::vector<lbug::binder::BoundInsertInfo, std::__1::allocator<lbug::binder::BoundInsertInfo>>&) in liblbug.a[24](bind_updating_clause.cpp.o)
    lbug::binder::Binder::bindInsertRel(std::__1::shared_ptr<lbug::binder::RelExpression>, std::__1::vector<lbug::binder::BoundInsertInfo, std::__1::allocator<lbug::binder::BoundInsertInfo>>&) in liblbug.a[24](bind_updating_clause.cpp.o)
    lbug::json_extension::jsonifyAsString(lbug::json_extension::JsonMutWrapper&, lbug::common::ValueVector const&, unsigned long long) in liblbug.a[164](json_utils.cpp.o)
    lbug::json_extension::jsonify(lbug::json_extension::JsonMutWrapper&, lbug::common::ValueVector const&, unsigned long long) in liblbug.a[164](json_utils.cpp.o)
    lbug::json_extension::jsonify(lbug::json_extension::JsonMutWrapper&, lbug::common::ValueVector const&, unsigned long long) in liblbug.a[164](json_utils.cpp.o)
    lbug::json_extension::jsonify(lbug::json_extension::JsonMutWrapper&, lbug::common::ValueVector const&, unsigned long long) in liblbug.a[164](json_utils.cpp.o)
    lbug::json_extension::jsonify(lbug::json_extension::JsonMutWrapper&, lbug::common::ValueVector const&, unsigned long long) in liblbug.a[164](json_utils.cpp.o)
    lbug::json_extension::jsonify(lbug::json_extension::JsonMutWrapper&, lbug::common::ValueVector const&, unsigned long long) in liblbug.a[164](json_utils.cpp.o)
    lbug::json_extension::jsonify(lbug::json_extension::JsonMutWrapper&, lbug::common::ValueVector const&, unsigned long long) in liblbug.a[164](json_utils.cpp.o)
    lbug::json_extension::jsonify(lbug::json_extension::JsonMutWrapper&, lbug::common::ValueVector const&, unsigned long long) in liblbug.a[164](json_utils.cpp.o)
    lbug::json_extension::jsonify(lbug::json_extension::JsonMutWrapper&, lbug::common::ValueVector const&, unsigned long long) in liblbug.a[164](json_utils.cpp.o)
    lbug::json_extension::jsonify(lbug::json_extension::JsonMutWrapper&, lbug::common::ValueVector const&, unsigned long long) in liblbug.a[164](json_utils.cpp.o)
    lbug::json_extension::jsonify(lbug::json_extension::JsonMutWrapper&, lbug::common::ValueVector const&, unsigned long long) in liblbug.a[164](json_utils.cpp.o)
    ...
"_unsafe_yyjson_val_pool_grow", referenced from:
    lbug::binder::Binder::bindInsertNode(std::__1::shared_ptr<lbug::binder::NodeExpression>, std::__1::vector<lbug::binder::BoundInsertInfo, std::__1::allocator<lbug::binder::BoundInsertInfo>>&) in liblbug.a[24](bind_updating_clause.cpp.o)
    lbug::binder::Binder::bindInsertNode(std::__1::shared_ptr<lbug::binder::NodeExpression>, std::__1::vector<lbug::binder::BoundInsertInfo, std::__1::allocator<lbug::binder::BoundInsertInfo>>&) in liblbug.a[24](bind_updating_clause.cpp.o)
    lbug::binder::Binder::bindInsertNode(std::__1::shared_ptr<lbug::binder::NodeExpression>, std::__1::vector<lbug::binder::BoundInsertInfo, std::__1::allocator<lbug::binder::BoundInsertInfo>>&) in liblbug.a[24](bind_updating_clause.cpp.o)
    lbug::binder::Binder::bindInsertRel(std::__1::shared_ptr<lbug::binder::RelExpression>, std::__1::vector<lbug::binder::BoundInsertInfo, std::__1::allocator<lbug::binder::BoundInsertInfo>>&) in liblbug.a[24](bind_updating_clause.cpp.o)
    lbug::binder::Binder::bindInsertRel(std::__1::shared_ptr<lbug::binder::RelExpression>, std::__1::vector<lbug::binder::BoundInsertInfo, std::__1::allocator<lbug::binder::BoundInsertInfo>>&) in liblbug.a[24](bind_updating_clause.cpp.o)
    lbug::binder::Binder::bindInsertRel(std::__1::shared_ptr<lbug::binder::RelExpression>, std::__1::vector<lbug::binder::BoundInsertInfo, std::__1::allocator<lbug::binder::BoundInsertInfo>>&) in liblbug.a[24](bind_updating_clause.cpp.o)
    lbug::json_extension::jsonifyAsString(lbug::json_extension::JsonMutWrapper&, lbug::common::ValueVector const&, unsigned long long) in liblbug.a[164](json_utils.cpp.o)
    ...
"_yyjson_locate_pos", referenced from:
    lbug::json_extension::invalidJsonError(char const*, unsigned long, yyjson_read_err*) in liblbug.a[164](json_utils.cpp.o)
"_yyjson_mut_doc_free", referenced from:
    lbug::json_extension::JsonMutWrapper::~JsonMutWrapper() in liblbug.a[164](json_utils.cpp.o)
"_yyjson_mut_doc_imut_copy", referenced from:
    lbug::binder::Binder::bindInsertNode(std::__1::shared_ptr<lbug::binder::NodeExpression>, std::__1::vector<lbug::binder::BoundInsertInfo, std::__1::allocator<lbug::binder::BoundInsertInfo>>&) in liblbug.a[24](bind_updating_clause.cpp.o)
    lbug::binder::Binder::bindInsertRel(std::__1::shared_ptr<lbug::binder::RelExpression>, std::__1::vector<lbug::binder::BoundInsertInfo, std::__1::allocator<lbug::binder::BoundInsertInfo>>&) in liblbug.a[24](bind_updating_clause.cpp.o)
"_yyjson_mut_doc_new", referenced from:
    lbug::json_extension::JsonMutWrapper::JsonMutWrapper() in liblbug.a[164](json_utils.cpp.o)
"_yyjson_read_opts", referenced from:
    lbug::json_extension::stringToJson(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in liblbug.a[164](json_utils.cpp.o)
"_yyjson_val_mut_copy", referenced from:
    lbug::json_extension::jsonify(lbug::json_extension::JsonMutWrapper&, lbug::common::ValueVector const&, unsigned long long) in liblbug.a[164](json_utils.cpp.o)
"_yyjson_write_opts", referenced from:
    lbug::json_extension::jsonToString(lbug::json_extension::JsonWrapper const&) in liblbug.a[164](json_utils.cpp.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

(full logs [here](https://github.com/user-attachments/files/25937631/ladybug-rust.log))

This was working fine on kuzu v0.11.3. Seemingly it also works fine on ladybug v0.14.1.

Is this a permanent limitation or something that could be resolved?

It was very helpful in my project to have the embedded json support that kuzu added at the end, and your addition of the json extension to core is seemingly related to the issues here. So I would prefer not to need ladybug v0.14 with the external json extension.

### Are there known steps to reproduce?

```bash
cargo new ladybug-rust
cd ladybug-rust
```

add something to `src/main.rs` that uses ladybug, like

```rust
fn main() {
    let db = lbug::Database::in_memory(lbug::SystemConfig::default()).unwrap();
    let conn = lbug::Connection::new(&db).unwrap();
    let res = conn
        .query("CREATE NODE TABLE Users(name STRING PRIMARY KEY);")
        .unwrap()
        .get_num_columns();
    println!("ladybug version: {} ({})", lbug::VERSION, res);
}
```

```bash
# this works
cargo add lbug@0.14.1
cargo run

# but if i upgrade...
cargo add lbug@0.15.0
# ... then this doesn't
cargo run
```
